language: go

go:
  - 1.14.x

script:
  - go test -v ./...
  - CGO_ENABLED=0 GOARCH=amd64 go build -o demo
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t braveheart01815/demo:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag braveheart01815/demo:latest braveheart01815/demo:$GIT_SHA
  - docker push braveheart01815/demo:latest
  - docker push braveheart01815/demo:$GIT_SHA

services:
- docker